import type { Metadata } from "next";

import "./globals.css";
import { WalletProvider } from "@/providers/WalletProvider";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "TSender",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <Header />
          {children}
        </WalletProvider>
      </body>
    </html>
  );
}
